name: Build
on:
  push:
    branches:
      - main
jobs:
  bulid-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # build.py requires msbuild
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: python3 build.py

  bulid-mac:
    runs-on: macos-12
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: python3 build.py

  bulid-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: python3 build.py
